### PR TITLE
Add a verbose warning for calling rollout.rollout on image environments

### PR DESCRIPTION
**Pull request by dan-pandori**
## Description

Add a better warning message for the common issue of calling rollout.rollout using the environment instead of the expert's get_env() method.
https://github.com/HumanCompatibleAI/imitation/issues/599

## Testing

Added a test and also used the repro script from the issue and confirmed that you get a nice error message now. Ex:
```
ValueError: Policy and environment observation shape mismatch. This is likely caused by https://github.com/HumanCompatibleAI/imitation/issues/599. If encountering this from rollout.rollout, try calling:
rollout.rollout(expert, expert.get_env(), ...) instead of
rollout.rollout(expert, env, ...)

Policy observation shape: (4, 84, 84) 
Environment observation shape: (84, 84, 4)
```

### CODE REVIEW

**Comment by dan-pandori** [comment]
@AdamGleave, ready for you to take a look. Also of course feel free to hand this off to someone else to review, I'm still just not super sure who is the right match for these reviews.

**Review by anshradh — APPROVED** [review]
LGTM! I think you can add a `# pragma: no cover` to get around the code coverage check btw (not sure why it thinks the added code isn't covered in the first place though, so might be a deeper issue here I'm missing).

**Review by AdamGleave — APPROVED** [review]
The code coverage happens because you only test that the error message occurs, not that it _doesn't_ occur and the original exception is raised when you have some different mismatch.

I'd weakly vote in favour of adding another test to check it provides original exception on other kinds of shape mismatch, but otherwise it LGTM.

**Comment by dan-pandori** [comment]
Mm, that makes sense. Added a test for that case.

I didn't add a third test for the branch where both the correct observation space and the one passed have a shape of length 3, but don't line up in a way that corresponds to this common mistake. But I can add it if you'd prefer.

**Comment by dan-pandori** [comment]
OK, codecov's demands are more draconian than I anticipated, so I extended the test to cover this case as well.

**Comment by AdamGleave** [comment]
Thanks! We can override codecov check when it's obviously stupid, but in this case the additional test seems simple enough anyway.

**Pull request merged**
