### PR TITLE
Update AutoROM to latest version

### PR DESCRIPTION
**Pull request by taufeeque9**
## Description

The recent release of AutoROM (v0.5.5) installs smoothly on Windows CI without throwing the previously encountered [error](https://app.circleci.com/pipelines/github/HumanCompatibleAI/imitation/3337/workflows/3fc3bf36-c306-4b03-80fa-c85c7cb2102e/jobs/12295) introduced with v0.5.3. The following [note](https://github.com/Farama-Foundation/AutoROM/issues/39) from the AutoROM repo mentions that all the issues should be solved if one has the `Roms.tar.gz` file available. The error we got with earlier versions of AutoROM suggested that the package didn't have the permissions to overwrite the pre-downloaded Roms.

>   AutoROM will download the Atari 2600 ROMs.
  They will be installed to:
          C:\Users\circleci\AppData\Local\Temp\pip-install-bnzarn2y\autorom-accept-rom-license_ff30b5dc32b749289ce968ae3ea8efd6\build\bdist.win-amd64\wheel\AutoROM\roms
> 
>  Existing ROMs will be overwritten.
  error: [WinError 5] Access is denied: 'C:\\Users\\circleci\\AppData\\Local\\Temp\\pip-install-bnzarn2y\\autorom-accept-rom-license_ff30b5dc32b749289ce968ae3ea8efd6\\./Roms.tar.gz'

So the latest release checks if the ROMs have already been installed before attempting to reinstall or overwrite, which fixes the error we get. The only issue is downloading the ROMs in the first place. Downloading the ROMs through torrent fails sometimes, and so we need to pre-download torrent as done [here](https://github.com/Farama-Foundation/AutoROM/pull/40).

### CODE REVIEW

**Comment by AdamGleave** [comment]
Nice, thanks for looking into this @taufeeque9! Tag me when it's ready for review :)

**Comment by jjshoots** [comment]
Hi all, just noticed this thread. While we cannot make the tar.gz file publicly available nor can we guarantee the existence of the Roms.tar.gz file on GDrive, if you send me a message on Discord (jat#3180), I'm sure I can get you the link to the file itself that you can then use in CI.

**Review by Rocamonde — COMMENTED** [review]
Looks good, just wondering about the base64 line?

**Comment by taufeeque9** [comment]
The latest version of AutoROM (v0.6.0) fixes all the issues by downloading ROMs directly without using torrent. So I have reverted the changes in the PR and added v0.6 of AutoROM to the requirement. Everything seems to be working fine!

**Review by Rocamonde — APPROVED** [review]
LGTM

**Pull request merged**
