### PR TITLE
Upgrade to python 3.8 and ubuntu 20.04

### PR DESCRIPTION
**Pull request by ernestum**
@AdamGleave would you push the image to dockerhub? Maybe first with the tag base-alpha so we can test it in this PR before applying to the entire repository?

### CODE REVIEW

**Review by AdamGleave — APPROVED** [review]
LGTM, feel free to merge once tested on CI with new Docker image

**Comment by AdamGleave** [comment]
I've hopefully fixed pytype issue by updating setup.cfg.

I'm not sure what's up with the error with get_schedule_fn, maybe SB3 version changed too and that caused some new issue?

**Comment by ernestum** [comment]
Pytype needed some more attention and the `get_schedule_fn` issue could be resolved by re-training the experts.
No idea where the coverage changes come from though.

**Review by AdamGleave — APPROVED** [review]
LGTM

**Pull request merged**
