### PR TITLE
Stricter linting

### LINKED ISSUE #30: lint grep for `import pdb`
Add something like `find ... -exec grep "import pdb" \{\};` ... to `ci/lint.sh` to catch `# import pdb; pdb.set_trace()` automatically.

Here's an easy way to get `grep` to return a nonzero exit code upon finding a pattern: `https://unix.stackexchange.com/a/74038/110511`.

### PR DESCRIPTION
**Pull request by AdamGleave**
Closes #30 (PDB check) and improves docstring linting (Sphinx only emits warnings for most problems, which previously were displayed in the logs only but now also fail the linter).

### CODE REVIEW

**Comment by AdamGleave** [comment]
Inspired by https://julien.danjou.info/the-best-flake8-extensions/ and https://github.com/DmytroLitvinov/awesome-flake8-extensions

**Comment by shwang** [comment]
I'm pleasantly surprised that something like `flake8-debugger` exists!

**Comment by shwang** [comment]
Thanks for fixing up my docstring warnings, I tried fixing them myself but didn't seem to understand the errors enough

**Comment by shwang** [comment]
image

**Pull request merged**
