### PR TITLE
docs: Sync release notes to documentation (fixes #488)

### LINKED ISSUE #488: Sync release notes from GitHub to the docs
Use [this tool](https://github.com/ewjoachim/sphinx-github-changelog)

### PR DESCRIPTION
**Pull request by tomtseng**
This PR uses [sphinx-github-changelog](https://github.com/ewjoachim/sphinx-github-changelog) to sync release notes from GitHub releases to the documentation (fixes #488).

### CODE REVIEW

**Comment by tomtseng** [comment]
@AdamGleave:  in order for `sphinx-github-changelog` to work, you (or some other admin of this project) will have to set the `SPHINX_GITHUB_CHANGELOG_TOKEN` secret at https://readthedocs.org/dashboard/imitation/environmentvariables/ to be a GitHub API token with read-access to the repository.

Relevant `sphinx-github-changelog` documentation:
- https://github.com/ewjoachim/sphinx-github-changelog#how--the-short-version
- https://github.com/ewjoachim/sphinx-github-changelog#extension-options-confpy

Relevant Read the Docs documentation:
- https://docs.readthedocs.io/en/stable/environment-variables.html#user-defined-environment-variables

**Comment by AdamGleave** [comment]
I've made a machine user [AlignmentFundBot](https://github.com/alignmentfundbot) and granted it read-only access to `imitation`.

The `sphinx-github-changelog` project doesn't clearly specify what permissions the API token needs to have. However, the [GitHub API docs](https://developer.github.com/v3/repos/releases/) claims that "Information about published releases are available to everyone", so I've tried making a personal access token with no special permissions.

**Comment by AdamGleave** [comment]
API token seems to be working: https://imitation--510.org.readthedocs.build/en/510/development/release-notes.html

Tag me when it's out of draft and ready for a review.

**Comment by tomtseng** [comment]
Great, I just wanted to make sure `release-notes.html` looked good before un-drafting this — should be ready for review

**Review by AdamGleave — APPROVED** [review]
LGTM

**Pull request merged**
